name: Linux build

on:
  push:
  pull_request:

jobs:
  # Job name
  build:
    name: Linux build
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install packages
      run: sudo apt install cmake g++ make python3 autoconf automake
    
    - name: Build release
      run: ./build.py
